### ISSUE TITLE
LOGIN-2.1 Access restriction

### ISSUE THREAD

**Issue by anhvimac** [nikiada/SillyGeese-soen341projectF2023#19]
Buttons that lead to pages a user should not have access to should be hidden + inaccessible. Functionalities should only be usable by users who have the correct rights.

Story points: 3
Completed: 0

**Comment by FrancoMimir** [comment]
Scenario 1:
- Log in as a CLIENT user. 
-  - "Brokers" page is hidden,  listings and search still available.

Scenario 2:
- Login as an ADMIN user
- - page containing crud capabilities is available for selection.
