### ISSUE TITLE
User Story: "Search for brokers" 

### ISSUE THREAD

**Issue by FrancoMimir** [nikiada/SillyGeese-soen341projectF2023#38]
As a user, I would like to search for brokers so that I can find and connect with the right broker for my property related needs.

**Comment by FrancoMimir** [comment]
- [x] #39

**Comment by anhvimac** [comment]
### User Acceptance Flow

Scenario 1:
- User enters characters for a broker's name or email.
- - The list updates to display brokers with matching characters in their name or email.

**Comment by anhvimac** [comment]
#45
